version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VERSION_VARIANT: 3.11
        OS_VARIANT: bookworm

    volumes:
      - ..:/workspace  

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
